{% set name = "cpp-terminal" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/cpp-terminal/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 37615b2747acee8237ae065cb219aa244a82da1ea2c795bee36ec1b9bbc546c9

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/include/cpp-terminal/terminal.h  # [unix]
    - if not exist %LIBRARY_PREFIX%/include/cpp-terminal/terminal.h (exit 1) else (exit 0)  # [win]

about:
  home: https://github.com/certik/terminal
  license: MIT
  license_file: LICENSE
  summary: Terminal is small cross-platform, header only C++ library for writing terminal applications.
  dev_url: https://github.com/certik/terminal

extra:
  recipe-maintainers:
    - wolfv
    - certik
